---
- hosts: cockpit
  tasks:
  - name: run serviceONE
    become: yes
    docker:
      docker_api_version: 1.18
      name: serviceONE
      image: tutum/hello-world
      state: reloaded
      ports: 80

  - name: run HAProxy
    become: yes
    docker:
      docker_api_version: 1.18
      name: reverse proxy
      image: haproxy
      state: reloaded
      ports: 80:80
