---
- hosts: cockpit
  tasks:  
  - name: update yum  
    sudo: yes
    yum: name=*

  - name: add epel extras
    sudo: yes
    yum: name=epel-release state=present

  - name: install ansible
    sudo: yes
    yum: name=ansible state=present

  - name: install docker
    sudo: yes
    yum: name=docker state=present

  - name: installer epel
    yum: name="https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"
         state=present
    sudo: yes
    ignore_errors: yes

  - name: install pip
    yum: name=python-pip state=present

  - name: install docker python
    pip: name=docker-py state=present

  - name: start docker
    sudo: yes
    service: name=docker enabled=true state=started    

  - name: install git
    sudo: yes
    yum: name=git state=present

  - name: create prosject folder
    tags: repo
    file: path=~/projects state=directory mode=0755

  - name: print default git repo to fetch
    debug: msg={{default_repo}}
    tags: repo

  - name: clone default git repo
    tags: repo
    git:  repo={{ default_repo }} 
          dest=/home/hosm/projects/default_repo
